# 开发环境配置
spring:
  # 数据源配置 - 开发环境
  datasource:
    url: jdbc:postgresql://localhost:5432/tradingsim_dev
    username: ${DB_USERNAME:tradingsim}
    password: ${DB_PASSWORD:tradingsim123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  
  # JPA配置 - 开发环境
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # Redis配置 - 开发环境
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

# 服务器配置 - 开发环境
server:
  port: 8080

# 日志配置 - 开发环境
logging:
  level:
    com.tradingsim: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/tradingsim-dev.log

# 应用配置 - 开发环境
tradingsim:
  game:
    max-sessions-per-user: 10
    session-timeout-minutes: 60
    
  market:
    cache-ttl-minutes: 5
    
  security:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "http://127.0.0.1:3000"
        - "http://127.0.0.1:5173"
        
  monitoring:
    metrics:
      enabled: true
    alerts:
      enabled: false