spring:
  # 数据源配置 - Docker环境
  datasource:
    url: jdbc:postgresql://tradingsim-db:5432/market
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
  
  # Redis配置 - Docker环境
  data:
    redis:
      host: tradingsim-redis
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 应用自定义配置
tradingsim:
  # 安全配置
  security:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "http://localhost:5174"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# 日志配置
logging:
  level:
    com.tradingsim: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN