# 测试环境配置
spring:
  # 数据源配置 - 测试环境
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA配置 - 测试环境
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Redis配置 - 测试环境 (使用嵌入式Redis)
  data:
    redis:
      host: localhost
      port: 6370
      database: 15

# 服务器配置 - 测试环境
server:
  port: 0  # 随机端口

# 日志配置 - 测试环境
logging:
  level:
    com.tradingsim: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.testcontainers: INFO

# 应用配置 - 测试环境
tradingsim:
  game:
    max-sessions-per-user: 100
    session-timeout-minutes: 5
    
  market:
    cache-ttl-minutes: 1
    
  security:
    cors:
      allowed-origins: "*"
      
  monitoring:
    metrics:
      enabled: false
    alerts:
      enabled: false